### ISSUE TITLE
Error during the login / account creation process

### ISSUE THREAD

**Issue by tmastrangelo** [CSNSE/csn-twitter#16]
Cannot login to app or create account. need to fix.

**Comment by tmastrangelo** [comment]
error persists at home wifi as well. this is not a connection problem. i plan to use the youtube tutorial and scour through it to find if maybe he ran into the problem at one point, because this issue is very individualized to my app, although I have tried solutions suggested by GPT and forums. I will continue searching, but until then, my app is unusable. That is all for now.

**Comment by tmastrangelo** [comment]
continued working on login functionality not working. I have narrowed it down to being due to security groups again, just like my database I believe. I referenced the original tutorial video to see if he had similar issues. I reviewed my emailService.ts file  as well, and I'm waiting on AWS support to respond to my email from this morning. I will most likely have this fixed by the end of the weekend, or hopefully sooner.

**Comment by tmastrangelo** [comment]
I created this flowchart to help AWS support and also anyone else helping me with this issue to troubleshoot.

![flowchart](https://github.com/CSNSE/csn-twitter/assets/71108068/acddb7fe-8a01-4fe6-a8b8-388e2b41123d)

**Comment by tmastrangelo** [comment]
Narrowing the issue down

✅ Email Service (SES) 
- working correctly because http://localhost:3000/auth/login works through thunder client, and sends an email to me with authentication code. 

🟡 JWT Secret 
- never changed, so should work properly. will wait on AWS support to check this one

✅ EC2 Instance
- up and running, no issues or warnings shown in aws console

(personal)
reference: [aws support](https://support.console.aws.amazon.com/support/home?region=us-east-1#/case/?displayId=171070963201928&language=en)

**Comment by tmastrangelo** [comment]
localhost is unable to handle http://localhost:3000/auth/authenticate with a simulated working email but incorrect code, it should have just returned "unauthorized" or "incorrect code" or something like that, but it crashed the server entirely. 

extended error:

tymastrangelo@tylers-macbook-pro TwitterBackend % npm run dev

> twitterbackend@1.0.0 dev
> nodemon src/index.ts

[nodemon] 3.1.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: ts,json
[nodemon] starting `ts-node src/index.ts`
Server ready at localhost:3000
/Users/tymastrangelo/Desktop/atcs/personal/TwitterBackend/node_modules/@prisma/client/runtime/library.js:122
`)}var Zi=({clientMethod:e,activeProvider:r})=>t=>{let n="",i;if(Array.isArray(t)){let[o,...s]=t;n=o,i={values:vt(s||[]),__prismaRawParameters__:!0}}else switch(r){case"sqlite":case"mysql":{n=t.sql,i={values:vt(t.values),__prismaRawParameters__:!0};break}case"cockroachdb":case"postgresql":case"postgres":{n=t.text,i={values:vt(t.values),__prismaRawParameters__:!0};break}case"sqlserver":{n=rl(t),i={values:vt(t.values),__prismaRawParameters__:!0};break}default:throw new Error(`The ${r} provider does not support ${e}`)}return i?.values?ol(`prisma.${e}(${n}, ${i.values})`):ol(`prisma.${e}(${n})`),{query:n,parameters:i}},sl={requestArgsToMiddlewareArgs(e){return[e.strings,...e.values]},middlewareArgsToRequestArgs(e){let[r,...t]=e;return new oe(r,t)}},al={requestArgsToMiddlewareArgs(e){return[e]},middlewareArgsToRequestArgs(e){return e[0]}};function Xi(e){return function(t){let n,i=(o=e)=>{try{return o===void 0||o?.kind==="itx"?n??(n=ll(t(o))):ll(t(o))}catch(s){return Promise.reject(s)}};return{then(o,s){return i().then(o,s)},catch(o){return i().catch(o)},finally(o){return i().finally(o)},requestTransaction(o){let s=i(o);return s.requestTransaction?s.requestTransaction(o):s},[Symbol.toStringTag]:"PrismaPromise"}}}function ll(e){return typeof e.then=="function"?e:Promise.resolve(e)}var ul={isEnabled(){return!1},getTraceParent(){return"00-10-10-00"},async createEngineSpan(){},getActiveContext(){},runInChildSpan(e,r){return r()}},eo=class{isEnabled(){return this.getGlobalTracingHelper().isEnabled()}getTraceParent(r){return this.getGlobalTracingHelper().getTraceParent(r)}createEngineSpan(r){return this.getGlobalTracingHelper().createEngineSpan(r)}getActiveContext(){return this.getGlobalTracingHelper().getActiveContext()}runInChildSpan(r,t){return this.getGlobalTracingHelper().runInChildSpan(r,t)}getGlobalTracingHelper(){return globalThis.PRISMA_INSTRUMENTATION?.helper??ul}};function cl(e){return e.includes("tracing")?new eo:ul}function pl(e,r=()=>{}){let t,n=new Promise(i=>t=i);return{then(i){return--e===0&&t(r()),i?.(n)}}}var Jm=["$connect","$disconnect","$on","$transaction","$use","$extends"],ml=Jm;function dl(e){return typeof e=="string"?e:e.reduce((r,t)=>{let n=typeof t=="string"?t:t.level;return n==="query"?r:r&&(t==="info"||r==="info")?"info":n},void 0)}var Cn=class{constructor(){this._middlewares=[]}use(r){this._middlewares.push(r)}get(r){return this._middlewares[r]}has(r){return!!this._middlewares[r]}length(){return this._middlewares.length}};var gl=_(ui());function Rn(e){return typeof e.batchRequestIdx=="number"}function Sn(e){return e===null?e:Array.isArray(e)?e.map(Sn):typeof e=="object"?Hm(e)?Wm(e):hr(e,Sn):e}function Hm(e){return e!==null&&typeof e=="object"&&typeof e.$type=="string"}function Wm({$type:e,value:r}){switch(e){case"BigInt":return BigInt(r);case"Bytes":return Buffer.from(r,"base64");case"DateTime":return new Date(r);case"Decimal":return new Te(r);case"Json":return JSON.parse(r);default:tr(r,"Unknown tagged value")}}function fl(e){if(e.action!=="findUnique"&&e.action!=="findUniqueOrThrow")return;let r=[];return e.modelName&&r.push(e.modelName),e.query.arguments&&r.push(ro(e.query.arguments)),r.push(ro(e.query.selection)),r.join("")}function ro(e){return`(${Object.keys(e).sort().map(t=>{let n=e[t];return typeof n=="object"&&n!==null?`(${t} ${ro(n)})`:t}).join(" ")})`}var Km={aggregate:!1,aggregateRaw:!1,createMany:!0,createOne:!0,deleteMany:!0,deleteOne:!0,executeRaw:!0,findFirst:!1,findFirstOrThrow:!1,findMany:!1,findRaw:!1,findUnique:!1,findUniqueOrThrow:!1,groupBy:!1,queryRaw:!1,runCommandRaw:!0,updateMany:!0,updateOne:!0,upsertOne:!0};function to(e){return Km[e]}var An=class{constructor(r){this.options=r;this.tickActive=!1;this.batches={}}request(r){let t=this.options.batchBy(r);return t?(this.batches[t]||(this.batches[t]=[],this.tickActive||(this.tickActive=!0,process.nextTick(()=>{this.dispatchBatches(),this.tickActive=!1}))),new Promise((n,i)=>{this.batches[t].push({request:r,resolve:n,reject:i})})):this.options.singleLoader(r)}dispatchBatches(){for(let r in this.batches){let t=this.batches[r];delete this.batches[r],t.length===1?this.options.singleLoader(t[0].request).then(n=>{n instanceof Error?t[0].reject(n):t[0].resolve(n)}).catch(n=>{t[0].reject(n)}):(t.sort((n,i)=>this.options.batchOrder(n.request,i.request)),this.options.batchLoader(t.map(n=>n.request)).then(n=>{if(n instanceof Error)for(let i=0;i<t.length;i++)t[i].reject(n);else for(let i=0;i<t.length;i++){let o=n[i];o instanceof Error?t[i].reject(o):t[i].resolve(o)}}).catch(n=>{for(let i=0;i<t.length;i++)t[i].reject(n)}))}}get[Symbol.toStringTag](){return"DataLoader"}};var zm=N("prisma:client:request_handler"),In=class{constructor(r,t){this.logEmitter=t,this.client=r,this.dataloader=new An({batchLoader:na(async({requests:n,customDataProxyFetch:i})=>{let{transaction:o,otelParentCtx:s}=n[0],a=n.map(p=>p.protocolQuery),l=this.client._tracingHelper.getTraceParent(s),u=n.some(p=>to(p.protocolQuery.action));return(await this.client._engine.requestBatch(a,{traceparent:l,transaction:Ym(o),containsWrite:u,customDataProxyFetch:i})).map((p,m)=>{if(p instanceof Error)return p;try{return this.mapQueryEngineResult(n[m],p)}catch(f){return f}})}),singleLoader:async n=>{let i=n.transaction?.kind==="itx"?hl(n.transaction):void 0,o=await this.client._engine.request(n.protocolQuery,{traceparent:this.client._tracingHelper.getTraceParent(),interactiveTransaction:i,isWrite:to(n.protocolQuery.action),customDataProxyFetch:n.customDataProxyFetch});return this.mapQueryEngineResult(n,o)},batchBy:n=>n.transaction?.id?`transaction-${n.transaction.id}`:fl(n.protocolQuery),batchOrder(n,i){return n.transaction?.kind==="batch"&&i.transaction?.kind==="batch"?n.transaction.index-i.transaction.index:0}})}async request(r){try{return await this.dataloader.request(r)}catch(t){let{clientMethod:n,callsite:i,transaction:o,args:s,modelName:a}=r;this.handleAndLogRequestError({error:t,clientMethod:n,callsite:i,transaction:o,args:s,modelName:a})}}mapQueryEngineResult({dataPath:r,unpacker:t},n){let i=n?.data,o=n?.elapsed,s=this.unpack(i,r,t);return process.env.PRISMA_CLIENT_GET_TIME?{data:s,elapsed:o}:s}handleAndLogRequestError(r){try{this.handleRequestError(r)}catch(t){throw this.logEmitter&&this.logEmitter.emit("error",{message:t.message,target:r.clientMethod,timestamp:new Date}),t}}handleRequestError({error:r,clientMethod:t,callsite:n,transaction:i,args:o,modelName:s}){if(zm(r),Zm(r,i)||r instanceof Le)throw r;if(r instanceof V&&Xm(r)){let l=yl(r.meta);Tn({args:o,errors:[l],callsite:n,errorFormat:this.client._errorFormat,originalMethod:t,clientVersion:this.client._clientVersion})}let a=r.message;if(n&&(a=Ar({callsite:n,originalMethod:t,isPanic:r.isPanic,showColors:this.client._errorFormat==="pretty",message:a})),a=this.sanitizeMessage(a),r.code){let l=s?{modelName:s,...r.meta}:r.meta;throw new V(a,{code:r.code,clientVersion:this.client._clientVersion,meta:l,batchRequestIdx:r.batchRequestIdx})}else{if(r.isPanic)throw new ue(a,this.client._clientVersion);if(r instanceof j)throw new j(a,{clientVersion:this.client._clientVersion,batchRequestIdx:r.batchRequestIdx});if(r instanceof R)throw new R(a,this.client._clientVersion);if(r instanceof ue)throw new ue(a,this.client._clientVersion)}throw r.clientVersion=this.client._clientVersion,r}sanitizeMessage(r){return this.client._errorFormat&&this.client._errorFormat!=="pretty"?(0,gl.default)(r):r}unpack(r,t,n){if(!r||(r.data&&(r=r.data),!r))return r;let i=Object.values(r)[0],o=t.filter(a=>a!=="select"&&a!=="include"),s=Sn(Ii(i,o));return n?n(s):s}get[Symbol.toStringTag](){return"RequestHandler"}};function Ym(e){if(e){if(e.kind==="batch")return{kind:"batch",options:{isolationLevel:e.isolationLevel}};if(e.kind==="itx")return{kind:"itx",options:hl(e)};tr(e,"Unknown transaction kind")}}function hl(e){return{id:e.id,payload:e.payload}}function Zm(e,r){return Rn(e)&&r?.kind==="batch"&&e.batchRequestIdx!==r.index}function Xm(e){return e.code==="P2009"||e.code==="P2012"}function yl(e){if(e.kind==="Union")return{kind:"Union",errors:e.errors.map(yl)};if(Array.isArray(e.selectionPath)){let[,...r]=e.selectionPath;return{...e,selectionPath:r}}return e}var El="5.11.0";var bl=El;function wl(e){return e.map(r=>{let t={};for(let n of Object.keys(r))t[n]=xl(r[n]);return t})}function xl({prisma__type:e,prisma__value:r}){switch(e){case"bigint":return BigInt(r);case"bytes":return Buffer.from(r,"base64");case"decimal":return new Te(r);case"datetime":case"date":return new Date(r);case"time":return new Date(`1970-01-01T${r}Z`);case"array":return r.map(xl);default:return r}}var Cl=_(Wi());var q=class extends Error{constructor(r){super(r+`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ^
PrismaClientInitializationError: 
Invalid `prisma.token.findUnique()` invocation in
/Users/tymastrangelo/Desktop/atcs/personal/TwitterBackend/src/routes/authRoutes.ts:106:43

  103 router.post('/authenticate', async (req, res) => {
  104   const {email, emailToken} = req.body;
  105 
→ 106   const dbEmailToken = await prisma.token.findUnique(
Timed out fetching a new connection from the connection pool. More info: http://pris.ly/d/connection-pool (Current connection pool timeout: 10, connection limit: 17)
    at In.handleRequestError (/Users/tymastrangelo/Desktop/atcs/personal/TwitterBackend/node_modules/@prisma/client/runtime/library.js:122:7154)
    at In.handleAndLogRequestError (/Users/tymastrangelo/Desktop/atcs/personal/TwitterBackend/node_modules/@prisma/client/runtime/library.js:122:6188)
    at In.request (/Users/tymastrangelo/Desktop/atcs/personal/TwitterBackend/node_modules/@prisma/client/runtime/library.js:122:5896)
    at async l (/Users/tymastrangelo/Desktop/atcs/personal/TwitterBackend/node_modules/@prisma/client/runtime/library.js:127:10871) {
  clientVersion: '5.11.0',
  errorCode: undefined
}
[nodemon] app crashed - waiting for file changes before starting...
rs
[nodemon] starting `ts-node src/index.ts`
Server ready at localhost:3000
